finchcollector/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>/', views.finch_detail, name='detail'),
    path('finches/create', views.FinchCreate.as_view(),name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name='finches_update'),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name='finches_delete'),
    path('cats/<int:finch_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('hats/', views.HatList.as_view(), name='hats_index'),
    path('hats/<int:pk>/', views.HatDetail.as_view(), name='hats_detail'),
    path('hats/create/', views.HatCreate.as_view(), name='hats_create'),
    path('hats/<int:pk>/update/', views.HatUpdate.as_view(), name='hats_update'),
    path('hats/<int:pk>/delete/', views.HatDelete.as_view(), name='hats_delete'),
    path('hats/<int:finch_id>/assoc_hat/<int:hat_id>/', views.assoc_hat, name='assoc_hat')
] 

main_app/models.py
from django.db import models
from django.urls import reverse

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Hat(models.Model):
  name = models.CharField(max_length=50)
  color = models.CharField(max_length=20)

def __str__(self):
    return self.name

def get_absolute_url(self):
    return reverse('toys_detail', kwargs={'pk': self.id})

# Create your models here.
class Finch(models.Model):
    name=models.CharField(max_length=100)
    typeof=models.CharField(max_length=100)
    description=models.TextField(max_length=250)
    age=models.IntegerField()
    #Adding Many to Many
    hats = models.ManyToManyField(Hat)

    def __str__(self):
        return self.name
    # Add this method
    def get_absolute_url(self):
        return reverse('detail', kwargs={'finch_id': self.id})

class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
    max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )

  finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_meal_display()} on {self.date}"

# change the default sort
  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Finch, Hat
from .forms import FeedingForm

# Add the following import
from django.http import HttpResponse


# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

# Add new view
def finches_index(request):
  finches = Finch.objects.all()
  return render(request, 'finches/index.html', { 'finches': finches })

def finch_detail(request, finch_id):
  finch = Finch.objects.get(id=finch_id)
  # Get the toys the cat doesn't have...
  # First, create a list of the toy ids that the cat DOES have
  id_list = finch.hats.all().values_list('id')
  # Now we can query for toys whose ids are not in the list using exclude
  hats_finch_doesnt_have = Hat.objects.exclude(id__in=id_list)
  feeding_form = FeedingForm()
  return render(request, 'finches/detail.html', {
    'finch': finch, 'feeding_form': feeding_form,
    # Add the toys to be displayed
    'hats': hats_finch_doesnt_have
  })

def add_feeding(request, finch_id):
  # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.finch_id = finch_id
    new_feeding.save()
  return redirect('detail', finch_id=finch_id)


class FinchCreate(CreateView):
  model = Finch
  fields = ['name','typeof', 'description', 'age']

class FinchUpdate(UpdateView):
  model = Finch
  # Let's disallow the renaming of a cat by excluding the name field!
  fields = ['typeof', 'description', 'age']

class FinchDelete(DeleteView):
  model = Finch
  success_url = '/finches/'

def assoc_hat(request, finch_id, hat_id):
  # Note that you can pass a toy's id instead of the whole toy object
  Finch.objects.get(id=finch_id).hats.add(hat_id)
  return redirect('detail', finch_id=finch_id)

class HatList(ListView):
  model = Hat

class HatDetail(DetailView):
  model = Hat

class HatCreate(CreateView):
  model = Hat
  fields = '__all__'
  success_url = "/hats/"

class HatUpdate(UpdateView):
  model = Hat
  fields = ['name', 'color']
  success_url = "/hats/"

class HatDelete(DeleteView):
  model = Hat
  success_url = '/hats/' 

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Finch Collector</h1>
<hr />
<p>Hire the Finch Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  {% load static %}

  <!DOCTYPE html>
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Finch Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header class="navbar-fixed">
      <nav>
        <div class="nav-wrapper">
          <ul>
            <li><a href="{% url 'home'%}" class="left brand-logo">&nbsp;&nbsp;FinchCollector</a></li>
          </ul>
          <ul class="right">
              <li><a href="{%url 'about'%}">About</a></li>
              <!-- new markup below -->
              <!-- new link below -->
              <li><a href="{% url 'about' %}">About</a></li>
                  <li><a href="{% url 'hats_create' %}">Add a Hat</a></li>
                  <li><a href="{% url 'hats_index' %}">View Allde Hats</a></li>
                  <li><a href="{% url 'finches_create' %}">Add a Finch</a></li>
                  <li><a href="{% url 'index' %}">View All My Finches</a></li>
          </ul>
        </div>
      </nav>
    </header>
    <main class="container">
      {% block content %}
      {% endblock %}
    </main>
    <footer class="page-footer">
      <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
    </footer>
  </body>
  </html>

main_app/templates/finches/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Finch Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>TypeOf: {{ finch.typeof }}</p>
        <p>Description: {{ finch.description }}</p>
        <p>Age: {{ finch.age }}</p>
      </div>
      <!-- Add the following markup -->
      <div class="card-action">
        <a href="{% url 'finches_update' finch.id %}">Edit</a>
        <a href="{% url 'finches_delete' finch.id %}">Delete</a>
      </div>
      <!-- New markup above -->
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' finch.id %}" method="POST">
      {% csrf_token %}
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>  
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in finch.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ finch.name }}'s Hats</h3>
    {% if finch.hats.count %}
      {% for hat in finch.hats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ hat.color }}">{{ hat.color }}</span> {{ hat.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Hats :(</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Hats</h3>
    {% if hats.count %}
      {% for hat in hats.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ hat.color }}">{{ hat.color }}</span> {{ hat.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_hat' finch.id hat.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{hat.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/finches/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Finches List</h1>

{% for finch in finches %}
  <div class="card">
    <a href="{% url 'detail' finch.id %}">
    <div class="card-content">
      <span class="card-title">{{ finch.name }}</span>
      <p>Type: {{ finch.typeof }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1

{% endblock %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Finch</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' finch.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/finch_form.html
{% extends 'base.html' %}

{% block content %}
 <!-- New if/else block -->
  {% if object %}
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
  <h1>Add Finch</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/hat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Hat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'hats_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/hat_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Hat Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ hat.name }}</span>
        <p>Color: {{ hat.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'hats_update' hat.id %}">Edit</a>
        <a href="{% url 'hats_delete' hat.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/hat_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Hat</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/hat_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Hat List</h1>

{% for hat in hat_list %}
  <a href="{% url 'hats_detail' hat.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ hat.name }}</span>
            <p>Color: {{ hat.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}